<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{ $campaign->name }}</title>@vite(['resources/css/app.css'])</head>
<body class="min-h-screen bg-slate-50 text-slate-900"><main class="mx-auto max-w-3xl px-6 py-12">
    <a class="text-sm font-semibold text-indigo-700" href="{{ route('admissions.public.campaigns') }}">← All campaigns</a><p class="mt-8 text-sm text-slate-500">{{ $campaign->institute->name }}</p><h1 class="mt-1 text-4xl font-bold">{{ $campaign->name }}</h1><p class="mt-3 text-slate-600">{{ $campaign->description }}</p>
    @if (session('application_started'))<section class="mt-8 rounded-2xl border border-emerald-300 bg-emerald-50 p-6"><h2 class="font-semibold">Draft started</h2><p class="mt-2 text-sm">Save this one-time access token securely. Resume and verification are delivered in the secure-access milestone.</p><code class="mt-3 block break-all rounded bg-white p-3 text-xs">{{ session('application_started.access_token') }}</code></section>@endif
    <section class="mt-8 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-xl font-semibold">Start an application</h2><p class="mt-2 text-sm text-slate-600">No ERP account is required. Email or mobile is required for secure follow-up.</p>
        @if ($errors->any())<div class="mt-4 rounded-lg bg-red-50 p-4 text-sm text-red-800"><ul>@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <form class="mt-6 grid gap-4 sm:grid-cols-2" method="post" action="{{ route('admissions.public.applications.store', $campaign) }}">@csrf
            <label class="text-sm font-medium">Given name<input class="mt-1 w-full rounded-lg border-slate-300" name="given_name" required value="{{ old('given_name') }}"></label><label class="text-sm font-medium">Family name<input class="mt-1 w-full rounded-lg border-slate-300" name="family_name" value="{{ old('family_name') }}"></label><label class="text-sm font-medium">Date of birth<input class="mt-1 w-full rounded-lg border-slate-300" name="date_of_birth" type="date" value="{{ old('date_of_birth') }}"></label><label class="text-sm font-medium">Email<input class="mt-1 w-full rounded-lg border-slate-300" name="email" type="email" value="{{ old('email') }}"></label><label class="text-sm font-medium">Mobile<input class="mt-1 w-full rounded-lg border-slate-300" name="mobile" value="{{ old('mobile') }}"></label><div class="sm:col-span-2"><button class="rounded-lg bg-indigo-600 px-5 py-3 font-semibold text-white" type="submit">Start draft</button></div>
        </form>
    </section>
</main></body></html>
