<?php

return [
    'defaults' => [
        'appearance_mode' => 'system',
        'theme_preset' => 'default',
        'font_family' => 'system',
        'font_scale' => '1.00',
        'line_height' => 'normal',
        'interface_density' => 'comfortable',
        'sidebar_mode' => 'auto',
        'navigation_style' => 'sidebar',
        'content_width' => 'standard',
        'card_radius' => 'soft',
        'high_contrast' => false,
        'reduced_motion' => false,
        'enhanced_focus' => false,
        'large_click_targets' => false,
        'underline_links' => false,
        'dyslexia_friendly_font' => false,
        'reduced_transparency' => false,
        'simplified_layout' => false,
    ],

    'font_families' => [
        'system' => [
            'code' => 'system',
            'name' => 'System UI',
            'css_font_family' => 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
            'fallback_family' => 'sans-serif',
            'is_system' => true,
            'is_dyslexia_friendly' => false,
        ],
        'inter' => [
            'code' => 'inter',
            'name' => 'Inter',
            'css_font_family' => 'Inter, ui-sans-serif, system-ui, sans-serif',
            'fallback_family' => 'sans-serif',
            'is_system' => false,
            'is_dyslexia_friendly' => false,
        ],
        'roboto' => [
            'code' => 'roboto',
            'name' => 'Roboto',
            'css_font_family' => 'Roboto, ui-sans-serif, system-ui, sans-serif',
            'fallback_family' => 'sans-serif',
            'is_system' => false,
            'is_dyslexia_friendly' => false,
        ],
        'open_sans' => [
            'code' => 'open_sans',
            'name' => 'Open Sans',
            'css_font_family' => 'Open Sans, ui-sans-serif, system-ui, sans-serif',
            'fallback_family' => 'sans-serif',
            'is_system' => false,
            'is_dyslexia_friendly' => false,
        ],
        'source_sans_3' => [
            'code' => 'source_sans_3',
            'name' => 'Source Sans 3',
            'css_font_family' => 'Source Sans 3, ui-sans-serif, system-ui, sans-serif',
            'fallback_family' => 'sans-serif',
            'is_system' => false,
            'is_dyslexia_friendly' => false,
        ],
        'noto_sans' => [
            'code' => 'noto_sans',
            'name' => 'Noto Sans',
            'css_font_family' => 'Noto Sans, ui-sans-serif, system-ui, sans-serif',
            'fallback_family' => 'sans-serif',
            'is_system' => false,
            'is_dyslexia_friendly' => false,
        ],
        'atkinson_hyperlegible' => [
            'code' => 'atkinson_hyperlegible',
            'name' => 'Atkinson Hyperlegible',
            'css_font_family' => 'Atkinson Hyperlegible, ui-sans-serif, system-ui, sans-serif',
            'fallback_family' => 'sans-serif',
            'is_system' => false,
            'is_dyslexia_friendly' => true,
        ],
    ],

    'font_scales' => [
        '0.90' => 'Small',
        '1.00' => 'Default',
        '1.10' => 'Large',
        '1.25' => 'Extra Large',
        '1.40' => 'Maximum',
    ],

    'line_heights' => [
        'compact' => 1.35,
        'normal' => 1.50,
        'relaxed' => 1.70,
    ],

    'interface_densities' => [
        'compact' => 0.85,
        'comfortable' => 1.00,
        'spacious' => 1.15,
    ],

    'content_widths' => [
        'standard' => '90rem',
        'wide' => '110rem',
        'full' => '100%',
    ],

    'card_radii' => [
        'square' => '0rem',
        'soft' => '0.75rem',
        'rounded' => '1.5rem',
    ],

    'theme_presets' => [
        'default' => [
            'name' => 'Default',
            'description' => 'System default theme using institution colours.',
        ],
        'academic_blue' => ['name' => 'Academic Blue', 'description' => 'Soft blue palette for academic use.'],
        'professional_navy' => ['name' => 'Professional Navy', 'description' => 'High contrast navy and slate tones.'],
        'modern_teal' => ['name' => 'Modern Teal', 'description' => 'Clean teal interface with neutral backgrounds.'],
        'minimal_neutral' => ['name' => 'Minimal Neutral', 'description' => 'Subtle neutral palette with calm accents.'],
        'soft_green' => ['name' => 'Soft Green', 'description' => 'Natural green palette with accessible contrast.' ],
        'high_contrast' => ['name' => 'High Contrast', 'description' => 'Maximum contrast for readability and accessibility.'],
    ],

    'safe_tokens' => [
        'ui_font_family',
        'ui_font_scale',
        'ui_line_height',
        'ui_letter_spacing',
        'ui_primary_50',
        'ui_primary_100',
        'ui_primary_200',
        'ui_primary_300',
        'ui_primary_400',
        'ui_primary_500',
        'ui_primary_600',
        'ui_primary_700',
        'ui_primary_800',
        'ui_primary_900',
        'ui_primary_950',
        'ui_secondary_50',
        'ui_secondary_100',
        'ui_secondary_200',
        'ui_secondary_300',
        'ui_secondary_400',
        'ui_secondary_500',
        'ui_secondary_600',
        'ui_secondary_700',
        'ui_secondary_800',
        'ui_secondary_900',
        'ui_secondary_950',
        'ui_surface',
        'ui_text',
        'ui_border_radius',
        'ui_density_factor',
        'ui_sidebar_width',
        'ui_content_max_width',
        'ui_motion_duration',
        'ui_focus_ring_width',
        'ui_focus_ring_offset',
    ],
];
